spring:
  profiles:
    active: dev
  application:
    name: tennis-app

  datasource:
    url: jdbc:postgresql://localhost:5433/tennisapp
    username: postgres
    password: password123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
api-tennis:
  url: https://api.api-tennis.com/tennis
  key: 23cb891ae7d98d3d7dc7669725d564089d326be1c23e44e9dd1d021fa934262f

scheduler:
  sync:
    tournaments-cron: "0 0 3 * * *"
    standings-cron: "0 0 5 * * MON"
    fixtures-cron: "0 0 4 * * *"
    livescores-delay-ms: 120000
    livescores-initial-delay-ms: 60000

cors:
  allowed-origins:
    - http://localhost:5173
    - http://localhost:3000