spring:
  application:
    name: tennis-app

  datasource:
    url: jdbc:postgresql://localhost:5433/tennisapp
    username: postgres
    password: password123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
api-tennis:
  url: https://api.api-tennis.com/tennis
  key: c011626c4573046a66e0ffaf860a81d1d9304edee3e78f6adfdf0fa5b0565c3a